settings:
  default_submit_button_label: Bidali
  default_reset_button_label: Garbitu
  default_delete_button_label: Ezabatu
  default_preview_next_button_label: Aurrebista
  default_preview_label: Aurrebista
  dialog_options:
    narrow:
      title: Estu
    normal:
      title: Arrunta
    wide:
      title: Zabal
element:
  default_more_title: Gehiago
